---
version: '3.9'
volumes:
  pgdata: {}
services:
  app:
    container_name: flask
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: [db]
    ports: [5000:5000]
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN=5000
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    command: pipenv run flask run
  db:
    container_name: postgres
    image: postgres:15.1
    restart: always
    volumes: [pgdata:/var/lib/postgresql/data]
    ports: [5432:5432]
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
