---
version: '3.9'
volumes:
  pgdata: {}
services:
  app:
    container_name: flask
    build: .
    depends_on: [db]
    ports: [5000:5000]
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    command: pipenv run flask run --host=0.0.0.0 --port=5000
  db:
    container_name: postgres
    image: postgres:15.1
    restart: always
    volumes: [pgdata:/var/lib/postgresql/data]
    ports: [5432:5432]
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
