---
openapi: 3.0.0
info:
  title: To-do list application
  description: An API about managing taska
  version: 1.0.0
servers:
  - url: /api/v1
components:
  schemas:
    EditTask:
      type: object
      required: [text, completed]
      properties:
        text:
          type: string
        completed:
          type: boolean
    EditTaskText:
      type: object
      required: [text]
      properties:
        text:
          type: string
    EditTaskStatus:
      type: object
      required: [completed]
      properties:
        completed:
          type: boolean
  parameters:
    id:
      name: id
      description: ID of the task
      in: path
      required: true
      schema:
        type: integer
paths:
  /task:
    get:
      operationId: view.index
      tags: [People]
      summary: Read all the tasks
      responses:
        '200':
          description: Successfully read tasks
    post:
      operationId: view.create
      tags: [People]
      summary: Create a task
      requestBody:
        description: Task to create
        required: true
        content:
          application/json:
            schema:
              x-body-name: task
              $ref: '#/components/schemas/EditTask'
      responses:
        '201':
          description: Successfully created a task
  /task/{id}:
    get:
      operationId: view.show
      tags: [People]
      summary: Read selected task
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Successfully read task
    delete:
      operationId: view.delete
      tags: [People]
      summary: Delete selected task
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '204':
          description: Successfully deleted task
  /task/{id}/update_text:
    put:
      operationId: view.update_text
      tags: [People]
      summary: Update selected task text
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Successfully updated task text
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: task
              $ref: '#/components/schemas/EditTaskText'
  /task/{id}/update_status:
    put:
      operationId: view.update_status
      tags: [People]
      summary: Update selected task status
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: Successfully updated task list status
      requestBody:
        content:
          application/json:
            schema:
              x-body-name: task
              $ref: '#/components/schemas/EditTaskStatus'
